export {default as bars} from "./icon-hamburger.svg" ;
export {default as close} from "./icon-close.svg" ;
export {default as logo } from "./logo-bookmark.svg" ;
export {default as hero } from "./illustration-hero.svg" ;
export {default as fe1 } from "./illustration-features-tab-1.svg" ;
export {default as fe2 } from "./illustration-features-tab-2.svg" ;
export {default as fe3 } from "./illustration-features-tab-3.svg" ;
export {default as chrome } from "./logo-chrome.svg" ;
export {default as firefox } from "./logo-firefox.svg" ;
export {default as opera } from "./logo-opera.svg" ;
export {default as errorIcon } from "./icon-error.svg" ;
export {default as successIcon } from "./icon-success.svg" ;
export {default as listCheck } from "./icon-list.svg" ;
export {default as singUpDes } from "./illustration-sign-up-desktop.svg" ;
export {default as singUpMob } from "./illustration-sign-up-mobile.svg" ;
export {default as avatar } from "./image-colton.jpg" ;
export {default as star } from "./icon-star.svg" ;
export {default as mobTop } from "./bg-pattern-top-mobile.svg" ;
export {default as mobBottom } from "./bg-pattern-bottom-mobile.svg" ;
export {default as descTop } from "./bg-pattern-top-desktop.svg" ;
export {default as descBottom } from "./bg-pattern-bottom-desktop.svg" ;
export {default as dashboard  } from "./illustration-dashboard.png" ;
